######################################################################################################################
# Project Euler
# Problem 3
# File name: PE_P3.py
# Compile: python PE_p3.py
# Programer: Alexis Lopez
# Description: Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
######################################################################################################################

print(r"Welcome to 'Project Euler' This is problem #3")

def Largest_Prime_Factor(number):
    # Defining variables
    test_number = number    # To keep for later use
    lpf = 1    # Test which prime numbers is divisible by
    
    #for test in range(0, number):
    while (1):
    
        if (number % lpf == 0):
            number = int(number / lpf)
        
        if (number == 1):
            break
        
        lpf += 1
    
    print("\nThe Largest prime factor of", test_number, "is:", lpf)

if __name__ == "__main__":
    Largest_Prime_Factor(600851475143)